# Generated by Django 5.0.3 on 2024-05-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_yourtube', '0002_video_videosession_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
    ]
